kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: s2i-build
  namespace: my-cicd
  selfLink: /apis/build.openshift.io/v1/namespaces/my-cicd/buildconfigs/s2i-build
  uid: fb931d5a-8796-11e9-997e-0a580a80008b
  resourceVersion: '9462361'
  creationTimestamp: '2019-06-05T13:36:54Z'
spec:
  triggers:
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/siddaram217/SpringMVCApp.git'
      ref: master
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:latest'
  output:
    to:
      kind: ImageStreamTag
      name: 'simple-webapp:latest'
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
  lastVersion: 2
